<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/transactions.php");
	include("$currDir/transactions_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('transactions');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "transactions";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`transactions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kids1`.`name`), CONCAT_WS('',   `kids1`.`name`), '') /* Kid */" => "kid",
		"if(`transactions`.`date`,date_format(`transactions`.`date`,'%d/%m/%Y'),'')" => "date",
		"`transactions`.`amount`" => "amount",
		"`transactions`.`description`" => "description",
		"`transactions`.`balance`" => "balance",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`transactions`.`id`',
		2 => '`kids1`.`name`',
		3 => '`transactions`.`date`',
		4 => '`transactions`.`amount`',
		5 => 5,
		6 => '`transactions`.`balance`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`transactions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kids1`.`name`), CONCAT_WS('',   `kids1`.`name`), '') /* Kid */" => "kid",
		"if(`transactions`.`date`,date_format(`transactions`.`date`,'%d/%m/%Y'),'')" => "date",
		"`transactions`.`amount`" => "amount",
		"`transactions`.`description`" => "description",
		"`transactions`.`balance`" => "balance",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`transactions`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kids1`.`name`), CONCAT_WS('',   `kids1`.`name`), '') /* Kid */" => "Kid",
		"`transactions`.`date`" => "Date",
		"`transactions`.`amount`" => "Amount",
		"`transactions`.`description`" => "Description",
		"`transactions`.`balance`" => "Balance",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`transactions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kids1`.`name`), CONCAT_WS('',   `kids1`.`name`), '') /* Kid */" => "kid",
		"if(`transactions`.`date`,date_format(`transactions`.`date`,'%d/%m/%Y'),'')" => "date",
		"`transactions`.`amount`" => "amount",
		"`transactions`.`description`" => "description",
		"`transactions`.`balance`" => "balance",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('kid' => 'Kid', );

	$x->QueryFrom = "`transactions` LEFT JOIN `kids` as kids1 ON `kids1`.`id`=`transactions`.`kid` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "transactions_view.php";
	$x->RedirectAfterInsert = "transactions_view.php?SelectedID=#ID#";
	$x->TableTitle = "Transactions";
	$x->TableIcon = "resources/table_icons/table_money.png";
	$x->PrimaryKey = "`transactions`.`id`";
	$x->DefaultSortField = '`transactions`.`date`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Kid", "Date", "Amount", "Description", "Balance");
	$x->ColFieldName = array('kid', 'date', 'amount', 'description', 'balance');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/transactions_templateTV.html';
	$x->SelectedTemplate = 'templates/transactions_templateTVS.html';
	$x->TemplateDV = 'templates/transactions_templateDV.html';
	$x->TemplateDVP = 'templates/transactions_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transactions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transactions' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transactions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transactions' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`transactions`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: transactions_init
	$render=TRUE;
	if(function_exists('transactions_init')) {
		$args=array();
		$render=transactions_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: transactions_header
	$headerCode='';
	if(function_exists('transactions_header')) {
		$args=array();
		$headerCode=transactions_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: transactions_footer
	$footerCode='';
	if(function_exists('transactions_footer')) {
		$args=array();
		$footerCode=transactions_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>